# permissions for end users to edit ignitionv3s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: khalkeon
    app.kubernetes.io/managed-by: kustomize
  name: ignitionv3-editor-role
rules:
- apiGroups:
  - metal.cobaltcore.dev
  resources:
  - ignitionv3s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.cobaltcore.dev
  resources:
  - ignitionv3s/status
  verbs:
  - get
