---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - list
  - patch
  - watch
- apiGroups:
  - metal.cobaltcore.dev
  resources:
  - ignitionv3s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.cobaltcore.dev
  resources:
  - ignitionv3s/finalizers
  verbs:
  - update
- apiGroups:
  - metal.cobaltcore.dev
  resources:
  - ignitionv3s/status
  verbs:
  - get
  - patch
  - update
